# Generated by Django 2.1.7 on 2019-06-20 08:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Teksti', max_length=255)),
                ('body', models.TextField()),
                ('public', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('source_lang', models.CharField(choices=[('fr', 'French'), ('fi', 'Finnish')], max_length=2, verbose_name='Source language')),
                ('target_lang', models.CharField(choices=[('fr', 'French'), ('fi', 'Finnish')], max_length=2, verbose_name='Target language')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapter_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chapter_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['public', 'title'],
            },
        ),
        migrations.CreateModel(
            name='LearningData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learned', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Learning Data',
                'ordering': ['word'],
            },
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lemma', models.CharField(max_length=255)),
                ('translation', models.CharField(max_length=255)),
                ('pos', models.CharField(choices=[('ADJ', 'Adjective'), ('ADP', 'Adposition'), ('ADV', 'Adverb'), ('AUX', 'Auxiliary'), ('CONJ', 'Conjunction'), ('CCONJ', 'Coordinating conjunction'), ('DET', 'Determiner'), ('INTJ', 'Interjection'), ('NOUN', 'Noun'), ('NUM', 'Numeral'), ('PART', 'Particle'), ('PRON', 'Pronoun'), ('PROPN', 'Proper noun'), ('SCONJ', 'Subordinating conjunction'), ('SYM', 'Symbol'), ('VERB', 'Verb'), ('X', 'Other'), ('SPACE', 'Space')], max_length=5, verbose_name='Part-of-speech')),
                ('gender', models.CharField(choices=[('f', 'Feminine'), ('m', 'Masculine'), ('n', 'Neuter')], max_length=1, null=True)),
                ('source_lang', models.CharField(choices=[('fr', 'French'), ('fi', 'Finnish')], max_length=2, verbose_name='Source language')),
                ('target_lang', models.CharField(choices=[('fr', 'French'), ('fi', 'Finnish')], max_length=2, verbose_name='Target language')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='word_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='word_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['lemma'],
            },
        ),
        migrations.CreateModel(
            name='WordProperties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, default='', max_length=255)),
                ('frequency', models.IntegerField(default=0)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocabulary.Chapter')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocabulary.Word')),
            ],
            options={
                'verbose_name_plural': 'Word Properties',
            },
        ),
        migrations.AddField(
            model_name='learningdata',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocabulary.Word'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='words',
            field=models.ManyToManyField(through='vocabulary.WordProperties', to='vocabulary.Word'),
        ),
        migrations.AlterUniqueTogether(
            name='word',
            unique_together={('lemma', 'pos', 'gender')},
        ),
        migrations.AlterUniqueTogether(
            name='learningdata',
            unique_together={('word', 'user')},
        ),
    ]
