# Generated by Django 2.1.7 on 2019-09-03 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0003_auto_20190903_1300'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='word',
            unique_together={('lemma', 'pos', 'gender', 'target_lang', 'source_lang')},
        ),
    ]
